/*
    filename	:clock_setting.c
	description	:Set the clock frequency 
	author		:apsis_team
	date		:18.10.2011
*/

#include <p18f46k22.h>
#include "P18F46K22generic.h" 
#include "clock_setting.h"



/******************************************************************
      Description: For setting the Oscillator frequency to the 4 MHZ
   
 *********************************************************************/
void  fn_Set_Clock_Frequency(void)
{
		/*
			OSCCON  = OSCCON_IDLEN_ENABLE | OSCCON_IRCF2_SET | OSCCON_IRCF1_CLR | OSCCON_IRCF0_SET | OSCCON_OSTS_INTOSC_RUNNING | OSCCON_HFIOFS_STABLE | OSCCON_SCS1_SET | OSCCON_SCS0_SET;
			OSCTUNE = OSCTUNE_INTSRC_INTRC | OSCTUNE_PLLEN_DISABLE | OSCTUNE_TUN5_CLR | OSCTUNE_TUN4_CLR | OSCTUNE_TUN3_CLR | OSCTUNE_TUN2_CLR | OSCTUNE_TUN1_CLR | OSCTUNE_TUN0_CLR;	//Oscillator runs at the factory calibrated frequency for HFINTOSC and MFINTOSC)
			OSCCON2 = OSCCONE2_PLLRDY_OSCILLATOR_CLOCK | OSCCONE2_SOSCRUN_OSCILLATOR_CLOCK | OSCCONE2_UNIMPLIMENTED | OSCCONE2_MFIOSEL_CLR | OSCCONE2_SOSCGO_DISABLE | OSCCONE2_PRISD_SET | OSCCONE2_MFIOFS_UNSTABLE | OSCCONE2_LFIOFS_UNSTABLE;	 		
		
		*/
	
	#if (FREQUENCY == FREQUENCY_16MHZ)
		{
			OSCCON  = OSCCON_IDLEN_ENABLE | OSCCON_IRCF2_SET | OSCCON_IRCF1_SET | OSCCON_IRCF0_SET | OSCCON_OSTS_INTOSC_RUNNING | OSCCON_HFIOFS_STABLE | OSCCON_SCS1_SET | OSCCON_SCS0_SET;
			OSCTUNE = OSCTUNE_INTSRC_INTRC | OSCTUNE_PLLEN_DISABLE | OSCTUNE_TUN5_CLR | OSCTUNE_TUN4_CLR | OSCTUNE_TUN3_CLR | OSCTUNE_TUN2_CLR | OSCTUNE_TUN1_CLR | OSCTUNE_TUN0_CLR;	//Oscillator runs at the factory calibrated frequency for HFINTOSC and MFINTOSC)
			OSCCON2 = OSCCONE2_PLLRDY_OSCILLATOR_CLOCK | OSCCONE2_SOSCRUN_OSCILLATOR_CLOCK | OSCCONE2_UNIMPLIMENTED | OSCCONE2_MFIOSEL_CLR | OSCCONE2_SOSCGO_DISABLE | OSCCONE2_PRISD_SET | OSCCONE2_MFIOFS_UNSTABLE | OSCCONE2_LFIOFS_UNSTABLE;	 		
		}
	#elif (FREQUENCY == FREQUENCY_8MHZ)
		{
			OSCCON  = OSCCON_IDLEN_ENABLE | OSCCON_IRCF2_SET | OSCCON_IRCF1_SET | OSCCON_IRCF0_CLR | OSCCON_OSTS_INTOSC_RUNNING | OSCCON_HFIOFS_STABLE | OSCCON_SCS1_SET | OSCCON_SCS0_SET;
			OSCTUNE = OSCTUNE_INTSRC_INTRC | OSCTUNE_PLLEN_DISABLE | OSCTUNE_TUN5_CLR | OSCTUNE_TUN4_CLR | OSCTUNE_TUN3_CLR | OSCTUNE_TUN2_CLR | OSCTUNE_TUN1_CLR | OSCTUNE_TUN0_CLR;	//Oscillator runs at the factory calibrated frequency for HFINTOSC and MFINTOSC)
			OSCCON2 = OSCCONE2_PLLRDY_OSCILLATOR_CLOCK | OSCCONE2_SOSCRUN_OSCILLATOR_CLOCK | OSCCONE2_UNIMPLIMENTED | OSCCONE2_MFIOSEL_CLR | OSCCONE2_SOSCGO_DISABLE | OSCCONE2_PRISD_SET | OSCCONE2_MFIOFS_UNSTABLE | OSCCONE2_LFIOFS_UNSTABLE;	 		
		}
	#elif (FREQUENCY == FREQUENCY_4MHZ)
		{
			OSCCON  = OSCCON_IDLEN_ENABLE | OSCCON_IRCF2_SET | OSCCON_IRCF1_CLR | OSCCON_IRCF0_SET | OSCCON_OSTS_INTOSC_RUNNING | OSCCON_HFIOFS_STABLE | OSCCON_SCS1_SET | OSCCON_SCS0_SET;
			OSCTUNE = OSCTUNE_INTSRC_INTRC | OSCTUNE_PLLEN_DISABLE | OSCTUNE_TUN5_CLR | OSCTUNE_TUN4_CLR | OSCTUNE_TUN3_CLR | OSCTUNE_TUN2_CLR | OSCTUNE_TUN1_CLR | OSCTUNE_TUN0_CLR;	//Oscillator runs at the factory calibrated frequency for HFINTOSC and MFINTOSC)
			OSCCON2 = OSCCONE2_PLLRDY_OSCILLATOR_CLOCK | OSCCONE2_SOSCRUN_OSCILLATOR_CLOCK | OSCCONE2_UNIMPLIMENTED | OSCCONE2_MFIOSEL_CLR | OSCCONE2_SOSCGO_DISABLE | OSCCONE2_PRISD_SET | OSCCONE2_MFIOFS_UNSTABLE | OSCCONE2_LFIOFS_UNSTABLE;	 		
		}
	#elif (FREQUENCY == FREQUENCY_2MHZ)
		{
			OSCCON  = OSCCON_IDLEN_ENABLE | OSCCON_IRCF2_SET | OSCCON_IRCF1_CLR | OSCCON_IRCF0_CLR | OSCCON_OSTS_INTOSC_RUNNING | OSCCON_HFIOFS_STABLE | OSCCON_SCS1_SET | OSCCON_SCS0_SET;
			OSCTUNE = OSCTUNE_INTSRC_INTRC | OSCTUNE_PLLEN_DISABLE | OSCTUNE_TUN5_CLR | OSCTUNE_TUN4_CLR | OSCTUNE_TUN3_CLR | OSCTUNE_TUN2_CLR | OSCTUNE_TUN1_CLR | OSCTUNE_TUN0_CLR;	//Oscillator runs at the factory calibrated frequency for HFINTOSC and MFINTOSC)
			OSCCON2 = OSCCONE2_PLLRDY_OSCILLATOR_CLOCK | OSCCONE2_SOSCRUN_OSCILLATOR_CLOCK | OSCCONE2_UNIMPLIMENTED | OSCCONE2_MFIOSEL_CLR | OSCCONE2_SOSCGO_DISABLE | OSCCONE2_PRISD_SET | OSCCONE2_MFIOFS_UNSTABLE | OSCCONE2_LFIOFS_UNSTABLE;	 		
		}
	#elif (FREQUENCY == FREQUENCY_1MHZ)
		{
			OSCCON  = OSCCON_IDLEN_ENABLE | OSCCON_IRCF2_CLR | OSCCON_IRCF1_SET | OSCCON_IRCF0_SET | OSCCON_OSTS_INTOSC_RUNNING | OSCCON_HFIOFS_STABLE | OSCCON_SCS1_SET | OSCCON_SCS0_SET;
			OSCTUNE = OSCTUNE_INTSRC_INTRC | OSCTUNE_PLLEN_DISABLE | OSCTUNE_TUN5_CLR | OSCTUNE_TUN4_CLR | OSCTUNE_TUN3_CLR | OSCTUNE_TUN2_CLR | OSCTUNE_TUN1_CLR | OSCTUNE_TUN0_CLR;	//Oscillator runs at the factory calibrated frequency for HFINTOSC and MFINTOSC)
			OSCCON2 = OSCCONE2_PLLRDY_OSCILLATOR_CLOCK | OSCCONE2_SOSCRUN_OSCILLATOR_CLOCK | OSCCONE2_UNIMPLIMENTED | OSCCONE2_MFIOSEL_CLR | OSCCONE2_SOSCGO_DISABLE | OSCCONE2_PRISD_SET | OSCCONE2_MFIOFS_UNSTABLE | OSCCONE2_LFIOFS_UNSTABLE;	 		
		]	
	#endif
	
	
}