
#define High	1
#define Low		0


//DAY1

//ANSELA – PORTA ANALOG SELECT REGISTER
#define ANSELA_RESERVED_BIT7		0X00		
#define ANSELA_RESERVED_BIT6		0X00
#define ANSELA_ANSA5_SET			0X20			//Analog Select bit
#define ANSELA_ANSA5_CLR			0X00
#define ANSELA_RESERVED_BIT4		0X00
#define ANSELA_ANSA3_SET			0X08
#define ANSELA_ANSA3_CLR			0X00
#define ANSELA_ANSA2_SET			0X04
#define ANSELA_ANSA2_CLR			0X00
#define ANSELA_ANSA1_SET			0X02
#define ANSELA_ANSA1_CLR			0X00
#define ANSELA_ANSA0_SET			0X01
#define ANSELA_ANSA0_CLR			0X00

//ANSELB – PORTB ANALOG SELECT REGISTER
#define ANSELB_RESERVED_BIT7		0X00		
#define ANSELB_RESERVED_BIT6		0X00
#define ANSELB_ANSB5_SET			0X20			//Analog Select bit 
#define ANSELB_ANSB5_CLR			0X00
#define ANSELB_ANSB4_SET			0X10			
#define ANSELB_ANSB4_CLR			0X00
#define ANSELB_ANSB3_SET			0X08
#define ANSELB_ANSB3_CLR			0X00
#define ANSELB_ANSB2_SET			0X04
#define ANSELB_ANSB2_CLR			0X00
#define ANSELB_ANSB1_SET			0X02
#define ANSELB_ANSB1_CLR			0X00
#define ANSELB_ANSB0_SET			0X01
#define ANSELB_ANSB0_CLR			0X00

//ANSELC – PORTC ANALOG SELECT REGISTER




//ANSELC – PORTC ANALOG SELECT REGISTER
# define ANSELC_ANSC7_SET			0X80			//Analog Select bit 
# define ANSELC_ANSC7_CLR			0X00
# define ANSELC_ANSC6_SET			0X40
# define ANSELC_ANSC6_CLR			0X00
# define ANSELC_ANSC5_SET			0X20
# define ANSELC_ANSC5_CLR			0X00
# define ANSELC_ANSC4_SET			0X10
# define ANSELC_ANSC4_CLR			0X00
# define ANSELC_ANSC3_SET			0X08
# define ANSELC_ANSC3_CLR			0X00
# define ANSELC_ANSC2_SET			0X04
# define ANSELC_ANSC2_CLR			0X00
# define ANSELC_RESERVED_BIT1		0X00
# define ANSELC_RESERVED_BIT0		0X00

//ANSELD – PORTD ANALOG SELECT REGISTER
# define ANSELD_ANSD7_SET			0X80		
# define ANSELD_ANSD7_CLR			0X00
# define ANSELD_ANSD6_SET			0X40
# define ANSELD_ANSD6_CLR			0X00
# define ANSELD_ANSD5_SET			0X20
# define ANSELD_ANSD5_CLR			0X00
# define ANSELD_ANSD4_SET			0X10
# define ANSELD_ANSD4_CLR			0X00
# define ANSELD_ANSD3_SET			0X08
# define ANSELD_ANSD3_CLR			0X00
# define ANSELD_ANSD2_SET			0X04
# define ANSELD_ANSD2_CLR			0X00
# define ANSELD_ANSD1_SET			0X02
# define ANSELD_ANSD1_CLR			0X00
# define ANSELD_ANSD0_SET			0X01
# define ANSELD_ANSD0_CLR			0X00

//ANSELE – PORTE ANALOG SELECT REGISTER
#define ANSELE_RESERVED_BIT7		0x00
#define ANSELE_RESERVED_BIT6		0x00
#define ANSELE_RESERVED_BIT5		0x00
#define ANSELE_RESERVED_BIT4		0x00
#define ANSELE_RESERVED_BIT3		0x00
#define ANSELE_ANSE2_SET			0x04
#define ANSELE_ANSE2_CLR			0x00
#define ANSELE_ANSE1_SET			0x02
#define ANSELE_ANSE1_CLR			0x00
#define ANSELE_ANSE0_SET			0x01
#define ANSELE_ANSE0_CLR			0x00

// OSCTUNE: OSCILLATOR TUNING REGISTER 
#define OSCTUNE_INTSRC_INTOSC 		0x80
#define OSCTUNE_INTSRC_INTRC 		0x00
#define OSCTUNE_PLLEN_ENABLE 		0x40
#define OSCTUNE_PLLEN_DISABLE 		0x00
#define OSCTUNE_TUN5_SET			0x20
#define OSCTUNE_TUN5_CLR			0x00
#define OSCTUNE_TUN4_SET			0x10
#define OSCTUNE_TUN4_CLR			0x00
#define OSCTUNE_TUN3_SET			0x08
#define OSCTUNE_TUN3_CLR			0x00
#define OSCTUNE_TUN2_SET			0x04
#define OSCTUNE_TUN2_CLR			0x00
#define OSCTUNE_TUN1_SET			0x02
#define OSCTUNE_TUN1_CLR			0x00
#define OSCTUNE_TUN0_SET			0x01
#define OSCTUNE_TUN0_CLR			0x00



//OSCCON REGISTER
#define OSCCON_IDLEN_ENABLE			0x80
#define OSCCON_IDLEN_DISABLE		0x00
#define OSCCON_IRCF2_SET			0x40	
#define OSCCON_IRCF2_CLR			0x00	
#define OSCCON_IRCF1_SET			0x20	
#define OSCCON_IRCF1_CLR			0x00	
#define OSCCON_IRCF0_SET			0x10	
#define OSCCON_IRCF0_CLR			0x00
#define OSCCON_OSTS_INTOSC_RUNNING		0x00
#define OSCCON_OSTS_FOSC_RUNNING	0x08
#define OSCCON_HFIOFS_STABLE			0X04
#define OSCCON_HFIOFS_UNSTABLE			0X00
#define OSCCON_SCS1_SET					0x02		
#define OSCCON_SCS1_CLR					0x00					
#define OSCCON_SCS0_SET					0x01		
#define OSCCON_SCS0_CLR					0x00		

//OSCCONE2 REGISTER
#define OSCCONE2_PLLRDY_4xPLL_CLOCK				0x80
#define OSCCONE2_PLLRDY_OSCILLATOR_CLOCK		0x00
#define OSCCONE2_SOSCRUN_SECONDARY_CLOCK		0x40
#define OSCCONE2_SOSCRUN_OSCILLATOR_CLOCK		0x00
#define OSCCONE2_UNIMPLIMENTED					0x00 
#define OSCCONE2_MFIOSEL_SET					0x10
#define OSCCONE2_MFIOSEL_CLR					0x00	
#define OSCCONE2_SOSCGO_ENABLE					0x08
#define OSCCONE2_SOSCGO_DISABLE					0x00	
#define OSCCONE2_PRISD_SET						0x04
#define OSCCONE2_PRISD_CLR						0x00		
#define OSCCONE2_MFIOFS_STABLE					0x02
#define OSCCONE2_MFIOFS_UNSTABLE				0x00
#define OSCCONE2_LFIOFS_STABLE					0x01
#define OSCCONE2_LFIOFS_UNSTABLE				0x00

//TXSTA1: TRANSMIT STATUS AND CONTROL REGISTER
#define TXSTA1_CSRC_SYN_MASTER		0X80
#define TXSTA1_CSRC_SYN_SLAVE		0X00
#define TXSTA1_TX9_9BIT_MODE		0X40
#define TXSTA1_TX9_8BIT_MODE		0X00
#define TXSTA1_TXEN_ENABLE			0X20
#define TXSTA1_TXEN_DISABLE			0X00
#define TXSTA1_SYNC_SET				0X10		//EUSART Mode Select bit
#define TXSTA1_SYNC_CLR				0X00
#define TXSTA1_SENDB_SYNC_BRK_CONTINUE	 0X08	//Send Break Character bit
#define TXSTA1_SENDB_SYNC_BRK_COMPLETE	 0X00
//TXSTA1_SENDB:Synchronous mode:Don’t care	
#define TXSTA1_BRGH_HIGH_SPEED		0X04		//High Baud Rate Select bit		
#define TXSTA1_BRGH_LOW_SPEED		0X00
//TXSTA_BRGH_SYN					UNUSED		//Synchronous mode:Unused in this mode
#define TXSTA1_TRMT_TSR_EMPTY		1
#define TXSTA1_TRMT_TSR_FULL		0
#define TXSTA1_TX9D_SET				0X01
#define TXSTA1_TX9D_CLR				0X00

//TXSTA1: TRANSMIT STATUS AND CONTROL REGISTER
#define TXSTA2_CSRC_SYN_MASTER		0X80
#define TXSTA2_CSRC_SYN_SLAVE		0X00
#define TXSTA2_TX9_9BIT_MODE		0X40
#define TXSTA2_TX9_8BIT_MODE		0X00
#define TXSTA2_TXEN_ENABLE			0X20
#define TXSTA2_TXEN_DISABLE			0X00
#define TXSTA2_SYNC_SET				0X10		//EUSART Mode Select bit
#define TXSTA2_SYNC_CLR				0X00
#define TXSTA2_SENDB_SYNC_BRK_CONTINUE	 0X08	//Send Break Character bit
#define TXSTA2_SENDB_SYNC_BRK_COMPLETE	 0X00
//TXSTA1_SENDB:Synchronous mode:Don’t care	
#define TXSTA2_BRGH_HIGH_SPEED		0X04		//High Baud Rate Select bit		
#define TXSTA2_BRGH_LOW_SPEED		0X00
//TXSTA_BRGH_SYN					UNUSED		//Synchronous mode:Unused in this mode
#define TXSTA2_TRMT_TSR_EMPTY		1
#define TXSTA2_TRMT_TSR_FULL		0
#define TXSTA2_TX9D_SET				0X01
#define TXSTA2_TX9D_CLR				0X00

//RCSTA1: RECEIVE STATUS AND CONTROL REGISTER
#define RCSTA1_SPEN_ENABLE						0X80		//Serial Port Enable bit
#define RCSTA1_SPEN_DISABLE						0X00
#define RCSTA1_RX9_9BIT_MODE					0X40		//9-bit Receive Enable bit
#define RCSTA1_RX9_8BIT_MODE					0X00
//RCSTA_SREN_ASYNC				DONT CARE
//RCSTA_SREN_SYNC_SLAVE			DONT CARE
#define RCSTA1_SREN_SYNC_MASTER_ENABLE			0X20		//Single Receive Enable bit
#define RCSTA1_SREN_SYNC_MASTER_DISABLE			0X00
#define RCSTA1_CREN_ASYNC_ENABLE				0X10		//Continuous Receive Enable bit
#define RCSTA1_CREN_ASYNC_DISABLE				0X00
#define RCSTA1_CREN_SYNC_ENABLE					0X10
#define RCSTA1_CREN_SYNC_DISABLE				0X00
//RCSTA1_ADDEN1_ASYNC_8BIT_MODE					DONT CARE	
#define RCSTA1_ADDEN_ASYNC_ENABLE_RX9			0X08		//Address Detect Enable bit
#define RCSTA1_ADDEN_ASYNC_DISABLE_RX9			0X00
#define RCSTA1_FERR_ERROR						1			//Framing Error bit
#define RCSTA1_FERR_NO_ERROR					0
#define RCSTA1_OERR_ERROR						1			//Overrun Error bit
#define RCSTA1_OERR_NO_ERROR					0
#define RCSTA1_RX9D_SET							1			//Ninth bit of Received Data
#define RCSTA1_RX9D_CLR							0

//RCSTA2: RECEIVE STATUS AND CONTROL REGISTER
#define RCSTA2_SPEN_ENABLE						0X80		//Serial Port Enable bit
#define RCSTA2_SPEN_DISABLE						0X00
#define RCSTA2_RX9_9BIT_MODE					0X40		//9-bit Receive Enable bit
#define RCSTA2_RX9_8BIT_MODE					0X00
//RCSTA_SREN_ASYNC				DONT CARE
//RCSTA_SREN_SYNC_SLAVE			DONT CARE
#define RCSTA2_SREN_SYNC_MASTER_ENABLE			0X20		//Single Receive Enable bit
#define RCSTA2_SREN_SYNC_MASTER_DISABLE			0X00
#define RCSTA2_CREN_ASYNC_ENABLE				0X10		//Continuous Receive Enable bit
#define RCSTA2_CREN_ASYNC_DISABLE				0X00
#define RCSTA2_CREN_SYNC_ENABLE					0X10
#define RCSTA2_CREN_SYNC_DISABLE				0X00
//RCSTA1_ADDEN1_ASYNC_8BIT_MODE					DONT CARE	
#define RCSTA2_ADDEN_ASYNC_ENABLE_RX9			0X08		//Address Detect Enable bit
#define RCSTA2_ADDEN_ASYNC_DISABLE_RX9			0X00
#define RCSTA2_FERR_ERROR						1			//Framing Error bit
#define RCSTA2_FERR_NO_ERROR					0
#define RCSTA2_OERR_ERROR						1			//Overrun Error bit
#define RCSTA2_OERR_NO_ERROR					0
#define RCSTA2_RX9D_SET							1			//Ninth bit of Received Data
#define RCSTA2_RX9D_CLR							0

//						
//BAUDCON1: BAUD RATE CONTROL REGISTER
#define BAUDCON_ABDOVF_TIMER_OVERFLOWED				0X80		//Auto-Baud Detect Overflow bit
#define BAUDCON_ABDOVF_TIMER_DID_NOT_OVERFLOWED		0X00
#define BAUDCON_RCIDL_IDLE						1
#define BAUDCON_RCIDL_ACTIVE					0
//UNDEFINED BIT
//BAUDCON_SCKP_ASYNC 						UNUSED
#define BAUDCON_SCKP_SYNC_HIGH					0X10
#define BAUDCON_SCKP_SYNC_LOW					0X00
#define BAUDCON_BRG16_BRG_16BIT					0X08
#define BAUDCON_BRG16_BRG_8BIT					0X00
//UNDEFINED BIT
//BAUDCON_WUE_SYNC							UNUSED
#define BAUDCON_WUE_ASYNC_ENABLE				0X02
#define BAUDCON_WUE_ASYNC_DISABLE				0X00
#define BAUDCON_ABDEN_ASYNC_ENABLE				0X01
#define BAUDCON_ABDEN_ASYNC_DISABLE				0X00
//DAY2
//ADCON0: A/D CONTROL REGISTER 0

#define	ADCON0_UNIMPLIMENTED			0X00
#define	ADCON0_CHS4_SET					0X40 		//CHS4:CHS0: Analog Channel Select bits	
#define	ADCON0_CHS4_CLR					0X00 	
#define	ADCON0_CHS3_SET					0X20 	
#define	ADCON0_CHS3_CLR					0X00
#define	ADCON0_CHS2_SET					0X10	
#define	ADCON0_CHS2_CLR					0X00
#define	ADCON0_CHS1_SET					0X08	
#define	ADCON0_CHS1_CLR					0X00
#define	ADCON0_CHS0_SET					0X04	
#define	ADCON0_CHS0_CLR					0X00
#define CHANNEL_AN0			ADCON0_CHS4_CLR|ADCON0_CHS3_CLR|ADCON0_CHS2_CLR|ADCON0_CHS1_CLR|ADCON0_CHS0_CLR		//channel_0 select bit.
#define CHANNEL_AN1			ADCON0_CHS4_CLR|ADCON0_CHS3_CLR|ADCON0_CHS2_CLR|ADCON0_CHS1_CLR|ADCON0_CHS0_SET		//channel_1 select bit.
#define CHANNEL_AN2			ADCON0_CHS4_CLR|ADCON0_CHS3_CLR|ADCON0_CHS2_CLR|ADCON0_CHS1_SET|ADCON0_CHS0_CLR		//channel_2 select bit.
#define CHANNEL_AN3			ADCON0_CHS4_CLR|ADCON0_CHS3_CLR|ADCON0_CHS2_CLR|ADCON0_CHS1_SET|ADCON0_CHS0_SET		//channel_3 select bit.
#define CHANNEL_AN4			ADCON0_CHS4_CLR|ADCON0_CHS3_CLR|ADCON0_CHS2_SET|ADCON0_CHS1_CLR|ADCON0_CHS0_CLR		//channel_5 select bit.#define	ADCON0_GO						0X02	//GO/DONE: A/D Conversion Status bit, When ADON = 1: 
#define CHANNEL_AN5			ADCON0_CHS4_CLR|ADCON0_CHS3_CLR|ADCON0_CHS2_SET|ADCON0_CHS1_CLR|ADCON0_CHS0_SET		//channel_6 select bit.
#define CHANNEL_AN6			ADCON0_CHS4_CLR|ADCON0_CHS3_CLR|ADCON0_CHS2_SET|ADCON0_CHS1_SET|ADCON0_CHS0_CLR		//channel_7 select bit.
#define CHANNEL_AN7			ADCON0_CHS4_CLR|ADCON0_CHS3_CLR|ADCON0_CHS2_SET|ADCON0_CHS1_SET|ADCON0_CHS0_SET		//channel_8 select bit.
#define CHANNEL_AN8			ADCON0_CHS4_CLR|ADCON0_CHS3_SET|ADCON0_CHS2_CLR|ADCON0_CHS1_CLR|ADCON0_CHS0_CLR		//channel_9 select bit.
#define CHANNEL_AN9			ADCON0_CHS4_CLR|ADCON0_CHS3_SET|ADCON0_CHS2_CLR|ADCON0_CHS1_CLR|ADCON0_CHS0_SET		//channel_10 select bit.
#define CHANNEL_AN10		ADCON0_CHS4_CLR|ADCON0_CHS3_SET|ADCON0_CHS2_CLR|ADCON0_CHS1_SET|ADCON0_CHS0_CLR		//channel_11 select bit.
#define CHANNEL_AN11		ADCON0_CHS4_CLR|ADCON0_CHS3_SET|ADCON0_CHS2_CLR|ADCON0_CHS1_SET|ADCON0_CHS0_SET		//channel_11 select bit.
#define CHANNEL_AN12		ADCON0_CHS4_CLR|ADCON0_CHS3_SET|ADCON0_CHS2_SET|ADCON0_CHS1_CLR|ADCON0_CHS0_CLR		//channel_12 select bit.
#define CHANNEL_AN13		ADCON0_CHS4_CLR|ADCON0_CHS3_SET|ADCON0_CHS2_SET|ADCON0_CHS1_CLR|ADCON0_CHS0_SET		//channel_13 select bit.
#define CHANNEL_AN14		ADCON0_CHS4_CLR|ADCON0_CHS3_SET|ADCON0_CHS2_SET|ADCON0_CHS1_SET|ADCON0_CHS0_CLR		//channel_14 select bit.
#define CHANNEL_AN15		ADCON0_CHS4_CLR|ADCON0_CHS3_SET|ADCON0_CHS2_SET|ADCON0_CHS1_SET|ADCON0_CHS0_SET		//channel_15 select bit.
#define CHANNEL_AN16		ADCON0_CHS4_SET|ADCON0_CHS3_CLR|ADCON0_CHS2_CLR|ADCON0_CHS1_CLR|ADCON0_CHS0_CLR		//channel_16 select bit.
#define CHANNEL_AN17		ADCON0_CHS4_SET|ADCON0_CHS3_CLR|ADCON0_CHS2_CLR|ADCON0_CHS1_CLR|ADCON0_CHS0_SET		//channel_17 select bit.
#define CHANNEL_AN18		ADCON0_CHS4_SET|ADCON0_CHS3_CLR|ADCON0_CHS2_CLR|ADCON0_CHS1_SET|ADCON0_CHS0_CLR		//channel_18 select bit.
#define CHANNEL_AN19		ADCON0_CHS4_SET|ADCON0_CHS3_CLR|ADCON0_CHS2_CLR|ADCON0_CHS1_SET|ADCON0_CHS0_SET		//channel_19 select bit.
#define CHANNEL_AN20		ADCON0_CHS4_SET|ADCON0_CHS3_CLR|ADCON0_CHS2_SET|ADCON0_CHS1_CLR|ADCON0_CHS0_CLR		//channel_20 select bit.
#define CHANNEL_AN21		ADCON0_CHS4_SET|ADCON0_CHS3_CLR|ADCON0_CHS2_SET|ADCON0_CHS1_CLR|ADCON0_CHS0_SET		//channel_21 select bit.
#define CHANNEL_AN22		ADCON0_CHS4_SET|ADCON0_CHS3_CLR|ADCON0_CHS2_SET|ADCON0_CHS1_SET|ADCON0_CHS0_CLR		//channel_22 select bit.
#define CHANNEL_AN23		ADCON0_CHS4_SET|ADCON0_CHS3_CLR|ADCON0_CHS2_SET|ADCON0_CHS1_SET|ADCON0_CHS0_SET		//channel_23 select bit.
#define CHANNEL_AN24		ADCON0_CHS4_SET|ADCON0_CHS3_SET|ADCON0_CHS2_CLR|ADCON0_CHS1_CLR|ADCON0_CHS0_CLR		//channel_24 select bit.
#define CHANNEL_AN25		ADCON0_CHS4_SET|ADCON0_CHS3_SET|ADCON0_CHS2_CLR|ADCON0_CHS1_CLR|ADCON0_CHS0_SET		//channel_25 select bit.
#define CHANNEL_AN26		ADCON0_CHS4_SET|ADCON0_CHS3_SET|ADCON0_CHS2_CLR|ADCON0_CHS1_SET|ADCON0_CHS0_CLR		//channel_26 select bit.
#define CHANNEL_AN27		ADCON0_CHS4_SET|ADCON0_CHS3_SET|ADCON0_CHS2_CLR|ADCON0_CHS1_SET|ADCON0_CHS0_SET		//channel_27 select bit.
#define RESERVED			ADCON0_CHS4_SET|ADCON0_CHS3_SET|ADCON0_CHS2_SET|ADCON0_CHS1_CLR|ADCON0_CHS0_CLR		//Reserved
#define CTMU				ADCON0_CHS4_SET|ADCON0_CHS3_SET|ADCON0_CHS2_SET|ADCON0_CHS1_CLR|ADCON0_CHS0_SET		//CTMU
#define DAC					ADCON0_CHS4_SET|ADCON0_CHS3_SET|ADCON0_CHS2_SET|ADCON0_CHS1_SET|ADCON0_CHS0_CLR		//DAC
#define FVR_BUF2			ADCON0_CHS4_SET|ADCON0_CHS3_SET|ADCON0_CHS2_SET|ADCON0_CHS1_SET|ADCON0_CHS0_SET		//FVR BUF2 (1.024V/2.048V/2.096V Volt Fixed Voltage Reference)

#define ADCON0_GO						0x02	//start the convertion
#define ADCON0_DONE						0x00	//convertion finished
#define	ADCON0_ADON_ENABLE				0X01	//ADON: A/D On bit
#define	ADCON0_ADON_DISABLE				0X00



// ADCON1: A/D CONTROL REGISTER 1

#define ADCON1_TRIGSEL_CTMU				0x80
#define ADCON1_TRIGSEL_CCP5				0x00
#define ADCON1_UNIMPLIMENTED_BIT6		0X00
#define ADCON1_UNIMPLIMENTED_BIT5		0X00
#define ADCON1_UNIMPLIMENTED_BIT4		0X00

#define ADCON1_PVCFG_BIT3_SET				0x08 	//VCFG1: Voltage Reference Configuration bit (VREF- source)
#define ADCON1_PVCFG_BIT3_CLR				0X00
#define ADCON1_PVCFG_BIT2_SET				0X04
#define ADCON1_PVCFG_BIT2_CLR				0X00
#define ADC_VREF_CONNECTED_TO_INTERNAL_SIGNAL_AVDD 							(ADCON1_PVCFG_BIT3_CLR)|(ADCON1_PVCFG_BIT2_CLR)	
#define ADC_VREF_CONNECTED_TO_EXTERNAL_PIN_VREFPOS							(ADCON1_PVCFG_BIT3_CLR)|(ADCON1_PVCFG_BIT2_SET)			
#define ADC_VREF_CONNECTED_TO_INTERNAL_SIGNAL_FVR_BUF2						(ADCON1_PVCFG_BIT3_SET)|(ADCON1_PVCFG_BIT2_CLR)			
#define RESERVED_BY_DEFAULT_ADC_VREFPOS_CONNECTED_TO_INTERNAL SIGNAL_AVDD	(ADCON1_PVCFG_BIT3_SET)|(ADCON1_PVCFG_BIT2_SET)		

#define ADCON1_NVCFG0_BIT1_SET			0x02 	
#define ADCON1_NVCFG0_BIT1_CLR			0x00
#define ADCON1_NVCFG0_BIT0_SET			0x01
#define ADCON1_NVCFG0_BIT0_CLR			0x00   
#define ADC_VREFNEG_CONNECTED_TO_INTERNAL_SIGNAL_AVSS						(ADCON1_NVCFG0_BIT1_CLR)|(ADCON1_NVCFG0_BIT0_CLR)		
#define ADC VREFNEG_CONNECTED_TO_EXTERNAL_PIN_VREFNEG						(ADCON1_NVCFG0_BIT1_CLR)|(ADCON1_NVCFG0_BIT0_SET)	
#define RESERVED_BIT1															(ADCON1_NVCFG0_BIT1_SET)|(ADCON1_NVCFG0_BIT0_CLR)	
#define RESERVED_BIT0															ADCON1_NVCFG0_BIT1_SET|ADCON1_NVCFG0_BIT0_SET	

// ADCON2: A/D CONTROL REGISTER 2

#define ADCON2_ADFM_RIGHT				0X80	//ADFM: A/D Result Format Select bit
#define ADCON2_ADFM_LEFT				0X00
#define UNIMPLEMENTED					0x00
#define ADCON2_ACQT2_BIT5_SET			0X20	//ACQT2:ACQT0: A/D Acquisition Time Select bits
#define ADCON2_ACQT2_BIT5_CLR			0X00
#define ADCON2_ACQT1_BIT4_SET			0X10
#define ADCON2_ACQT1_BIT4_CLR			0X00
#define ADCON2_ACQT0_BIT3_SET			0X08
#define ADCON2_ACQT0_BIT3_CLR			0X00
#define ADCON2_TAD_0		ADCON2_ACQT2_BIT5_CLR|ADCON2_ACQT1_BIT4_CLR|ADCON2_ACQT0_BIT3_CLR
#define ADCON2_TAD_2		ADCON2_ACQT2_BIT5_CLR|ADCON2_ACQT1_BIT4_CLR|ADCON2_ACQT0_BIT3_SET
#define ADCON2_TAD_4		ADCON2_ACQT2_BIT5_CLR|ADCON2_ACQT1_BIT4_SET|ADCON2_ACQT0_BIT3_CLR	
#define ADCON2_TAD_6		ADCON2_ACQT2_BIT5_CLR|ADCON2_ACQT1_BIT4_SET|ADCON2_ACQT0_BIT3_SET	
#define ADCON2_TAD_8		ADCON2_ACQT2_BIT5_SET|ADCON2_ACQT1_BIT4_CLR|ADCON2_ACQT0_BIT3_CLR		
#define ADCON2_TAD_12		ADCON2_ACQT2_BIT5_SET|ADCON2_ACQT1_BIT4_CLR|ADCON2_ACQT0_BIT3_SET
#define ADCON2_TAD_16		ADCON2_ACQT2_BIT5_SET|ADCON2_ACQT1_BIT4_SET|ADCON2_ACQT0_BIT3_CLR
#define ADCON2_TAD_20		ADCON2_ACQT2_BIT5_SET|ADCON2_ACQT1_BIT4_SET|ADCON2_ACQT0_BIT3_SET	
		
#define ADCON2_ADCS2_BIT2_SET			0X04	//ADCS2:ADCS0: A/D Conversion Clock Select bits
#define ADCON2_ADCS2_BIT2_CLR			0X00
#define ADCON2_ADCS1_BIT1_SET			0X02
#define ADCON2_ADCS1_BIT1_CLR			0X00
#define ADCON2_ADCS0_BIT0_SET			0X01
#define ADCON2_ADCS0_BIT2_CLR			0X00
#define ADCON2_FOSC_BY_2	ADCON2_ADCS2_BIT2_CLR|ADCON2_ADCS1_BIT1_CLR|ADCON2_ADCS0_BIT2_CLR
#define ADCON2_FOSC_BY_8	ADCON2_ADCS2_BIT2_CLR|ADCON2_ADCS1_BIT1_CLR|ADCON2_ADCS0_BIT2_SET
#define ADCON2_FOSC_BY_32	ADCON2_ADCS2_BIT2_CLR|ADCON2_ADCS1_BIT1_SET|ADCON2_ADCS0_BIT2_CLR
#define ADCON2_FOSC_RC_1		ADCON2_ADCS2_BIT2_CLR|ADCON2_ADCS1_BIT1_SET|ADCON2_ADCS0_BIT2_SET
#define ADCON2_FOSC_BY_4	ADCON2_ADCS2_BIT2_SET|ADCON2_ADCS1_BIT1_CLR|ADCON2_ADCS0_BIT2_CLR
#define ADCON2_FOSC_BY_16	ADCON2_ADCS2_BIT2_SET|ADCON2_ADCS1_BIT1_CLR|ADCON2_ADCS0_BIT2_SET
#define ADCON2_FOSC_BY_64	ADCON2_ADCS2_BIT2_SET|ADCON2_ADCS1_BIT1_SET|ADCON2_ADCS0_BIT2_CLR
#define ADCON2_FOSC_RC_2		ADCON2_ADCS2_BIT2_SET|ADCON2_ADCS1_BIT1_SET|ADCON2_ADCS0_BIT2_SET

//INTCON: INTERRUPT CONTROL REGISTER
//#define INTCON_GIE_IPEN_LOW				0X80
//#define INTCON_GIE_IPEN_LOW				0X00
//#define INTCON_GIE_IPEN_HIGH			0X80
//#define INTCON_GIE_IPEN_HIGH			0X00


//CMCON: COMPARATOR CONTROL REGISTER

#define CMCON_C2OUT_SET					0x80	//C2OUT: Comparator 2 Output bit	(dependant on C2INV status)
#define CMCON_C2OUT_CLR					0x00
#define CMCON_C1OUT_SET					0x40	//C1OUT: Comparator 1 Output bit	(dependant on C1INV status)
#define CMCON_C1OUT_CLR					0x00
#define CMCON_C2INV_INVERT				0x20$	//C2INV: Comparator 2 Output Inversion bit
#define CMCON_C2INV_NOT_INVERT			0x00
#define CMCON_C1INV_INVERT				0x10	//C1INV: Comparator 1 Output Inversion bit
#define CMCON_C1INV_NOT_INVERT			0x00
#define CMCON_CIS_INPUT_RA3RA2			0x08	//CIS: Comparator Input Switch bit
#define CMCON_CIS_NOT_INPUT_RA0RA1		0x00
#define CMCON_CM2_SET					0X04	//CM2:CM0: Comparator Mode bits
#define CMCON_CM2_CLR					0X00
#define CMCON_CM1_SET					0X02
#define CMCON_CM1_CLR					0X00
#define CMCON_CM0_SET					0X01
#define CMCON_CM0_CLR					0X00

//CVRCON: COMPARATOR VOLTAGE REFERENCE CONTROL REGISTER

#define CVRCON_CVREN_ENABLE					0X80	//CVREN: Comparator Voltage Reference Enable bit
#define CVRCON_CVREN_DISABLE				0X00
#define CVRCON_CVROE_ENABLE						0X40	//CVROE: Comparator VREF Output Enable bit
#define CVRCON_CVROE_DISABLE				0X00
#define CVRCON_CVRR_LOW_RANGE				0X20	//CVRR: Comparator VREF Range Selection bit
#define CVRCON_CVRR_HIGH_RANGE				0X00
#define CVRCON_CVRSS_VREFPOSNEG				0X10$	//CVRSS: Comparator VREF Source Selection bit
#define CVRCON_CVRSS_VREFVDDVSS				0X00
#define CVRCON_CVR3_SET						0X08	//CVR3:CVR0: Comparator VREF Value Selection bits (0 = (CVR3:CVR0) = 15) 
#define CVRCON_CVR3_CLR						0X00
#define CVRCON_CVR2_SET						0X04
#define CVRCON_CVR2_CLR						0X00
#define CVRCON_CVR1_SET						0X02
#define CVRCON_CVR1_CLR						0X00
#define CVRCON_CVR0_SET						0X01
#define CVRCON_CVR0_CLR						0X00

//HLVDCON: HIGH/LOW-VOLTAGE DETECT CONTROL REGISTER

#define HLVDCON_VDIRMAG_EQUAL_ABOVE			0X80	//VDIRMAG: Voltage Direction Magnitude Select bit
#define HLVDCON_VDIRMAG_EQUAL_BELOW			0X00 
//BIT6 UNDEFINED/UNIMPLEMENTED
#define HLVDCON_IRVST_GENERATE_INT			0X01$	//Internal Reference Voltage Stable Flag bit
#define HLVDCON_IRVST_NOT_GENERATE_INT		0X00
#define HLVDCON_IHLVDEN_ENABLE				0X10 	// High/Low-Voltage Detect Power Enable bit
#define HLVDCON_IHLVDEN_DISABLE				0X00
#define HLVDCON_HLVDL3_SET					0X08	//HLVDL3:HLVDL0: Voltage Detection Limit bits
#define HLVDCON_HLVDL3_CLR					0X00
#define HLVDCON_HLVDL2_SET					0X04
#define HLVDCON_HLVDL2_CLR					0X00
#define HLVDCON_HLVDL1_SET					0X02
#define HLVDCON_HLVDL1_CLR					0X00
#define HLVDCON_HLVDL0_SET					0X01
#define HLVDCON_HLVDL0_CLR					0X00

//CONFIG1H: CONFIGURATION REGISTER 1 HIGH (BYTE ADDRESS 300001h)

#define	CONFIG1H_IESO_ENABLE				0X80 	//IESO: Internal/External Oscillator Switchover bit
#define	CONFIG1H_IESO_DISABLE				0X00
#define	CONFIG1H_FCMEN_ENABLE				0X40	//FCMEN: Fail-Safe Clock Monitor Enable bit
#define	CONFIG1H_FCMEN_DISABLE				0X00
//BIT5 & BIT4 UNDEFINED/UNIMPLEMENTED
#define	CONFIG1H_FOSC3_SET					0X08	//FOSC3:FOSC0: Oscillator Selection bits
#define	CONFIG1H_FOSC3_CLR					0X00
#define	CONFIG1H_FOSC2_SET					0X04
#define	CONFIG1H_FOSC2_CLR					0X00
#define	CONFIG1H_FOSC1_SET					0X02
#define	CONFIG1H_FOSC1_CLR					0X00
#define	CONFIG1H_FOSC0_SET					0X01
#define	CONFIG1H_FOSC0_CLR					0X00

//CONFIG2L: CONFIGURATION REGISTER 2 LOW (BYTE ADDRESS 300002h) 

//BIT7 & BIT6 & BIT5  UNDEFINED/UNIMPLEMENTED
#define CONFIG2L_BORV1_SET					0X10	//BORV1:BORV0: Brown-out Reset Voltage bits
#define CONFIG2L_BORV1_CLR					0X00
#define CONFIG2L_BORV0_SET					0X08	
#define CONFIG2L_BORV0_CLR					0X00
#define CONFIG2L_BOREN1_SET					0X04	//BOREN1:BOREN0: Brown-out Reset Enable bits
#define CONFIG2L_BOREN1_CLR					0X00
#define CONFIG2L_BOREN0_SET					0X02
#define CONFIG2L_BOREN0_CLR					0X00
#define CONFIG2L_PWRTEN_ENABLE				0X00	//PWRTEN: Power-up Timer Enable bit
#define CONFIG2L_PWRTEN_DISABLE				0X01

//CONFIG2H: CONFIGURATION REGISTER 2 HIGH (BYTE ADDRESS 300003h)

//BIT7 & BIT6 & BIT5  UNDEFINED/UNIMPLEMENTED
#define CONFIG2H_WDTPS3_SET					0X10	//WDTPS3:WDTPS0: Watchdog Timer Postscale Select bits
#define CONFIG2H_WDTPS3_CLR					0X00
#define CONFIG2H_WDTPS2_SET					0X08
#define CONFIG2H_WDTPS2_CLR					0X00
#define CONFIG2H_WDTPS1_SET					0X04
#define CONFIG2H_WDTPS1_CLR					0X00
#define CONFIG2H_WDTPS0_SET					0X02
#define CONFIG2H_WDTPS0_CLR					0X00
#define CONFIG2H_WDTEN_ENABLE				0X01	//WDTEN: Watchdog Timer Enable bit
#define CONFIG2H_WDTEN_DISABLE				0X00

//CONFIG3H: CONFIGURATION REGISTER 3 HIGH (BYTE ADDRESS 300005h)

#define CONFIG3H_MCLRE_ENABLE				0X80	//MCLRE: MCLR Pin Enable bit 
#define CONFIG3H_MCLRE_DISABLE				0X00
//BIT6 & BIT5 & BIT4 & BIT3  UNDEFINED/UNIMPLEMENTED
#define CONFIG3H_LPT1OSC_ENABLE				0X04	//LPT1OSC: Low-Power Timer1 Oscillator Enable bit
#define CONFIG3H_LPT1OSC_DISABLE			0X00
#define CONFIG3H_PBADEN_ENABLE				0X02	//PBADEN: PORTB A/D Enable bit 
#define CONFIG3H_PBADEN_DISABLE				0X00
#define CONFIG3H_CCP2MX_RC1					0X01	//CCP2MX: CCP2 MUX bit
#define CONFIG3H_CCP2MX_RB3					0X00

//CONFIG4L: CONFIGURATION REGISTER 4 LOW (BYTE ADDRESS 300006h)

#define CONFIG4L_DEBUG_ENABLE				0X00	//DEBUG(BAR): Background Debugger Enable bit
#define CONFIG4L_DEBUG_DISABLE				0X80
#define CONFIG4L_XINST_ENABLE				0X40	//XINST: Extended Instruction Set Enable bit
#define CONFIG4L_XINST_DISABLE				0X00
//BIT56 & BIT4 & BIT3  UNDEFINED/UNIMPLEMENTED
#define CONFIG4L_LVP_ENABLE					0X04	//LVP: Single-Supply ICSP™ Enable bit
#define CONFIG4L_LVP_DISABLE				0X00
// BIT1  UNDEFINED/UNIMPLEMENTED
#define CONFIG4L_STVREN_ENABLE				0X01	//STVREN: Stack Full/Underflow Reset Enable bit
#define CONFIG4L_STVREN_DISABLE				0X00

//LATD

#define LATD_LATD7_SET						0x80
#define LATD_LATD7_CLR						0x00
#define LATD_LATD6_SET						0x40
#define LATD_LATD6_CLR						0x00
#define LATD_LATD5_SET						0x20
#define LATD_LATD5_CLR						0x00
#define LATD_LATD4_SET						0x10
#define LATD_LATD4_CLR						0x00
#define LATD_LATD3_SET						0x08
#define LATD_LATD3_CLR						0x00
#define LATD_LATD2_SET						0x04
#define LATD_LATD2_CLR						0x00
#define LATD_LATD1_SET						0x02
#define LATD_LATD1_CLR						0x00
#define LATD_LATD0_SET						0x01
#define LATD_LATD0_CLR						0x00


//TRISD
#define TRISD_TRISD7_SET					0x80
#define TRISD_TRISD7_CLR					0x00
#define TRISD_TRISD6_SET					0x40
#define TRISD_TRISD6_CLR					0x00
#define TRISD_TRISD5_SET					0x20
#define TRISD_TRISD5_CLR					0x00
#define TRISD_TRISD4_SET					0x10
#define TRISD_TRISD4_CLR					0x00
#define TRISD_TRISD3_SET					0x08
#define TRISD_TRISD3_CLR					0x00
#define TRISD_TRISD2_SET					0x04
#define TRISD_TRISD2_CLR					0x00
#define TRISD_TRISD1_SET					0x02
#define TRISD_TRISD1_CLR					0x00
#define TRISD_TRISD0_SET					0x01
#define TRISD_TRISD0_CLR					0x00

//SSP1STAT: SSP1 STATUS REGISTER

#define SSP1STAT_SMP_SET_SPI_MASER_MODE			0X80			//SPI Data Input Sample bit
#define SSP1STAT_SMP_CLR_SPI_MASER_MODE			0X00
#define SSP1STAT_SMP_CLR_SPI_SLAVE_MODE			0X00
#define SSP1STAT_SMP_SET_I2C_MODE				0X80
#define SSP1STAT_SMP_CLR_I2C_MODE				0X00
#define SSP1STAT_CKE_SET_SPI_MODE				0X40			//SPI Clock Edge Select bit (SPI mode only)
#define SSP1STAT_CKE_CLR_SPI_MODE				0X00
#define SSP1STAT_CKE_SET_I2C_MODE				0X40
#define SSP1STAT_CKE_CLR_I2C_MODE				0X00	
#define SSP1STAT_D_TO_A_SET_I2C_MODE				0X20			//Data/Address bit (I2C mode only)
#define SSP1STAT_D_TO_A_CLR_I2C_MODE				0X00
#define SSP1STAT_P_SET_I2C_MODE					0X10			//Stop bit
#define SSP1STAT_P_CLR_I2C_MODE					0X00
#define SSP1STAT_S_SET_I2C_MODE					0X08			//Start bit
#define SSP1STAT_S_CLR_I2C_MODE					0X00
#define SSP1STAT_RW_SET_I2C_MASTER_MODE		0X04			//Read/Write bit information (I2C mode only)
#define SSP1STAT_RW_CLR_I2C_MASTER_MODE		0X00
#define SSP1STAT_RW_SET_I2C_SLAVE_MODE			0X04
#define SSP1STAT_RW_CLR_I2C_SLAVE_MODE			0X00
#define SSP1STAT_UA_SET_I2C_MODE				0X02			//Update Address bit (10-bit I2C mode only)
#define SSP1STAT_UA_CLR_I2C_MODE				0X00
#define SSP1STAT_BF_SET_RECEIVE_SPI_OR_I2C_MODE				0X01	//Buffer Full Status bit
#define SSP1STAT_BF_CLR_RECEIVE_SPI_OR_I2C_MODE				0X00
#define SSP1STAT_BF_SET_TRANSMIT_I2C_MODE					0X01
#define SSP1STAT_BF_CLR_TRANSMIT_I2C_MODE					0X00

//SSP2STAT: SSP2 STATUS REGISTER

#define SSP2STAT_SMP_SET_SPI_MASER_MODE			0X80			//SPI Data Input Sample bit
#define SSP2STAT_SMP_CLR_SPI_MASER_MODE			0X00
#define SSP2STAT_SMP_CLR_SPI_SLAVE_MODE			0X00
#define SSP2STAT_SMP_SET_I2C_MODE				0X80
#define SSP2STAT_SMP_CLR_I2C_MODE				0X00
#define SSP2STAT_CKE_SET_SPI_MODE				0X40			//SPI Clock Edge Select bit (SPI mode only)
#define SSP2STAT_CKE_CLR_SPI_MODE				0X00
#define SSP2STAT_CKE_SET_I2C_MODE				0X40
#define SSP2STAT_CKE_CLR_I2C_MODE				0X00	
#define SSP2STAT_D_TO_A_SET_I2C_MODE				0X20			//Data/Address bit (I2C mode only)
#define SSP2STAT_D_TO_A_CLR_I2C_MODE				0X00
#define SSP2STAT_P_SET_I2C_MODE					0X10			//Stop bit
#define SSP2STAT_P_CLR_I2C_MODE					0X00
#define SSP2STAT_S_SET_I2C_MODE					0X08			//Start bit
#define SSP2STAT_S_CLR_I2C_MODE					0X00
#define SSP2STAT_RW_SET_I2C_MASTER_MODE		0X04			//Read/Write bit information (I2C mode only)
#define SSP2STAT_RW_CLR_I2C_MASTER_MODE		0X00
#define SSP2STAT_RW_SET_I2C_SLAVE_MODE			0X04
#define SSP2STAT_RW_CLR_I2C_SLAVE_MODE			0X00
#define SSP2STAT_UA_SET_I2C_MODE				0X02			//Update Address bit (10-bit I2C mode only)
#define SSP2STAT_UA_CLR_I2C_MODE				0X00
#define SSP2STAT_BF_SET_RECEIVE_SPI_OR_I2C_MODE				0X01	//Buffer Full Status bit
#define SSP2STAT_BF_CLR_RECEIVE_SPI_OR_I2C_MODE				0X00
#define SSP2STAT_BF_SET_TRANSMIT_I2C_MODE					0X01
#define SSP2STAT_BF_CLR_TRANSMIT_I2C_MODE					0X00

//SSP1CON1: SSP1 CONTROL REGISTER 1
#define SSP1CON1_WCOL_SET_MASTER_MODE			0X80			//Write Collision Detect bit
#define SSP1CON1_WCOL_CLR_MASTER_MODE			0X00
#define SSP1CON1_WCOL_SET_SLAVE_MODE			0X80
#define SSP1CON1_WCOL_CLR_SLAVE_MODE			0X00
#define SSP1CON1_SSP1OV_SET_SPI_MODE			0X40			//Receive Overflow Indicator bit
#define SSP1CON1_SSP1OV_CLR_SPI_MODE			0X00
#define SSP1CON1_SSP1OV_SET_I2C_MODE			0X40
#define SSP1CON1_SSP1OV_CLR_I2C_MODE			0X00
#define SSP1CON1_SSP1EN_SET_SPI_MODE			0X20			//Synchronous Serial Port Enable bit
#define SSP1CON1_SSP1EN_CLR_SPI_MODE			0X00
#define SSP1CON1_SSP1EN_SET_I2C_MODE			0X20
#define SSP1CON1_SSP1EN_CLR_I2C_MODE			0X00
#define SSP1CON1_CKP_SET_SPI_MODE				0X10			//Clock Polarity Select bit
#define SSP1CON1_CKP_CLR_SPI_MODE				0X00
#define SSP1CON1_CKP_SET_I2C_SLAVE_MODE			0X10			
#define SSP1CON1_CKP_CLR_I2C_SLAVE_MODE			0X00
#define SSP1CON1_CKP_CLR_I2C_MASTER_MODE		0X00			//Unused in the master mode
#define SSP1CON1_SSP1M_BIT3_SET			0X08
#define SSP1CON1_SSP1M_BIT3_CLR			0X00
#define SSP1CON1_SSP1M_BIT2_SET			0X04
#define SSP1CON1_SSP1M_BIT2_CLR			0X00
#define SSP1CON1_SSP1M_BIT1_SET			0X02
#define SSP1CON1_SSP1M_BIT1_CLR			0X00
#define SSP1CON1_SSP1M_BIT0_SET			0X01
#define SSP1CON1_SSP1M_BIT0_CLR			0X00
#define SSP1_SPI_MASTER_MODE_CLOCK_FOSC_BY_4				SSP1CON1_SSP1M_BIT3_CLR | SSP1CON1_SSP1M_BIT2_CLR | SSP1CON1_SSP1M_BIT1_CLR | SSP1CON1_SSP1M_BIT0_CLR
#define SSP1_SPI_MASTER_MODE_CLOCK_FOSC_BY_16				SSP1CON1_SSP1M_BIT3_CLR | SSP1CON1_SSP1M_BIT2_CLR | SSP1CON1_SSP1M_BIT1_CLR | SSP1CON1_SSP1M_BIT0_SET
#define SSP1_SPI_MASTER_MODE_CLOCK_FOSC_BY_64				SSP1CON1_SSP1M_BIT3_CLR | SSP1CON1_SSP1M_BIT2_CLR | SSP1CON1_SSP1M_BIT1_SET | SSP1CON1_SSP1M_BIT0_CLR
#define SSP1_SPI_MASTER_MODE_CLOCK_TMR2_OUTPUT_BY_2			SSP1CON1_SSP1M_BIT3_CLR | SSP1CON1_SSP1M_BIT2_CLR | SSP1CON1_SSP1M_BIT1_SET | SSP1CON1_SSP1M_BIT0_SET
#define SSP1_SPI_SLAVE_MODE_CLOCK_SCK1_PIN					SSP1CON1_SSP1M_BIT3_CLR | SSP1CON1_SSP1M_BIT2_SET | SSP1CON1_SSP1M_BIT1_CLR | SSP1CON1_SSP1M_BIT0_CLR
#define SSP1_SPI_SLAVE_MODE_CLOCK_SCK1_PIN1					SSP1CON1_SSP1M_BIT3_CLR | SSP1CON1_SSP1M_BIT2_SET | SSP1CON1_SSP1M_BIT1_CLR | SSP1CON1_SSP1M_BIT0_SET
#define	SSP1_I2C_SLAVE_MODE_7BIT_ADDRESS					SSP1CON1_SSP1M_BIT3_CLR | SSP1CON1_SSP1M_BIT2_SET | SSP1CON1_SSP1M_BIT1_SET | SSP1CON1_SSP1M_BIT0_CLR 
#define SSP1_I2C_SLAVE_MODE_10_BIT_ADDRESS					SSP1CON1_SSP1M_BIT3_CLR | SSP1CON1_SSP1M_BIT2_SET | SSP1CON1_SSP1M_BIT1_SET | SSP1CON1_SSP1M_BIT0_SET
#define SSP1_I2C_MASTER_MODE_CLOCK							SSP1CON1_SSP1M_BIT3_SET | SSP1CON1_SSP1M_BIT2_CLR | SSP1CON1_SSP1M_BIT1_CLR | SSP1CON1_SSP1M_BIT0_CLR
#define SSP1_RESERVED_0										SSP1CON1_SSP1M_BIT3_SET | SSP1CON1_SSP1M_BIT2_CLR | SSP1CON1_SSP1M_BIT1_CLR | SSP1CON1_SSP1M_BIT0_SET
#define SSP1_SPI_MASTER_MODE_CLOCK							SSP1CON1_SSP1M_BIT3_SET | SSP1CON1_SSP1M_BIT2_CLR | SSP1CON1_SSP1M_BIT1_SET | SSP1CON1_SSP1M_BIT0_CLR
#define SSP1_I2C_FIRMWARE_CONTROLLED_MASTER_MODE			SSP1CON1_SSP1M_BIT3_SET | SSP1CON1_SSP1M_BIT2_CLR | SSP1CON1_SSP1M_BIT1_SET | SSP1CON1_SSP1M_BIT0_SET
#define SSP1_RESERVED_1										SSP1CON1_SSP1M_BIT3_SET | SSP1CON1_SSP1M_BIT2_SET | SSP1CON1_SSP1M_BIT1_CLR | SSP1CON1_SSP1M_BIT0_CLR
#define SSP1_RESERVED_2									SSP1CON1_SSP1M_BIT3_SET | SSP1CON1_SSP1M_BIT2_SET | SSP1CON1_SSP1M_BIT1_CLR | SSP1CON1_SSP1M_BIT0_SET
#define SSP1_I2C_SLAVE_MODE_7_BIT_ADDRESS_WITH_START_AND_STOP_BIT_INTERRUPTS_ENABLED		SSP1CON1_SSP1M_BIT3_SET | SSP1CON1_SSP1M_BIT2_SET | SSP1CON1_SSP1M_BIT1_SET | SSP1CON1_SSP1M_BIT0_CLR
#define SSP1_I2C_SLAVE_MODE_10_BIT_ADDRESS_WITH_START_AND_STOP_BIT_INTERRUPTS_ENABLED	SSP1CON1_SSP1M_BIT3_SET | SSP1CON1_SSP1M_BIT2_SET | SSP1CON1_SSP1M_BIT1_SET | SSP1CON1_SSP1M_BIT0_SET

//SSP2CON1: SSP2 CONTROL REGISTER 1
#define SSP2CON1_WCOL_SET_MASTER_MODE			0X80			//Write Collision Detect bit
#define SSP2CON1_WCOL_CLR_MASTER_MODE			0X00
#define SSP2CON1_WCOL_SET_SLAVE_MODE			0X80
#define SSP2CON1_WCOL_CLR_SLAVE_MODE			0X00
#define SSP2CON1_SSP2OV_SET_SPI_MODE			0X40			//Receive Overflow Indicator bit
#define SSP2CON1_SSP2OV_CLR_SPI_MODE			0X00
#define SSP2CON1_SSP2OV_SET_I2C_MODE			0X40
#define SSP2CON1_SSP2OV_CLR_I2C_MODE			0X00
#define SSP2CON1_SSP2EN_SET_SPI_MODE			0X20			//Synchronous Serial Port Enable bit
#define SSP2CON1_SSP2EN_CLR_SPI_MODE			0X00
#define SSP2CON1_SSP2EN_SET_I2C_MODE			0X20
#define SSP2CON1_SSP2EN_CLR_I2C_MODE			0X00
#define SSP2CON1_CKP_SET_SPI_MODE				0X10			//Clock Polarity Select bit
#define SSP2CON1_CKP_CLR_SPI_MODE				0X00
#define SSP2CON1_CKP_SET_I2C_SLAVE_MODE			0X10			
#define SSP2CON1_CKP_CLR_I2C_SLAVE_MODE			0X00
#define SSP2CON1_CKP_CLR_I2C_MASTER_MODE		0X00			//Unused in the master mode
#define SSP2CON1_SSP2M_BIT3_SET			0X08
#define SSP2CON1_SSP2M_BIT3_CLR			0X00
#define SSP2CON1_SSP2M_BIT2_SET			0X04
#define SSP2CON1_SSP2M_BIT2_CLR			0X00
#define SSP2CON1_SSP2M_BIT1_SET			0X02
#define SSP2CON1_SSP2M_BIT1_CLR			0X00
#define SSP2CON1_SSP2M_BIT0_SET			0X01
#define SSP2CON1_SSP2M_BIT0_CLR			0X00
#define SSP2_SPI_MASTER_MODE_CLOCK_FOSC_BY_4						SSP2CON1_SSP2M_BIT3_CLR | SSP2CON1_SSP2M_BIT2_CLR | SSP2CON1_SSP2M_BIT1_CLR | SSP2CON1_SSP2M_BIT0_CLR
#define SSP2_SPI_MASTER_MODE_CLOCK_FOSC_BY_16						SSP2CON1_SSP2M_BIT3_CLR | SSP2CON1_SSP2M_BIT2_CLR | SSP2CON1_SSP2M_BIT1_CLR | SSP2CON1_SSP2M_BIT0_SET
#define SSP2_SPI_MASTER_MODE_CLOCK_FOSC_BY_64						SSP2CON1_SSP2M_BIT3_CLR | SSP2CON1_SSP2M_BIT2_CLR | SSP2CON1_SSP2M_BIT1_SET | SSP2CON1_SSP2M_BIT0_CLR
#define SSP2_SPI_MASTER_MODE_CLOCK_TMR2_OUTPUT_BY_2					SSP2CON1_SSP2M_BIT3_CLR | SSP2CON1_SSP2M_BIT2_CLR | SSP2CON1_SSP2M_BIT1_SET | SSP2CON1_SSP2M_BIT0_SET
#define SSP2_SPI_SLAVE_MODE_CLOCK_SCK2_PIN_SS1_PIN_CONTROL_ENABLED	SSP2CON1_SSP2M_BIT3_CLR | SSP2CON1_SSP2M_BIT2_SET | SSP2CON1_SSP2M_BIT1_CLR | SSP2CON1_SSP2M_BIT0_CLR
#define SSP2_SPI_SLAVE_MODE_CLOCK_SCK2_PIN_SS1_PIN_CONTROL_DISABLED	SSP2CON1_SSP2M_BIT3_CLR | SSP2CON1_SSP2M_BIT2_SET | SSP2CON1_SSP2M_BIT1_CLR | SSP2CON1_SSP2M_BIT0_SET
#define SSP2_I2C_SLAVE_MODE_7_BIT_ADDRESS							SSP2CON1_SSP2M_BIT3_CLR | SSP2CON1_SSP2M_BIT2_SET | SSP2CON1_SSP2M_BIT1_SET | SSP2CON1_SSP2M_BIT0_CLR
#define SSP2_I2C_SLAVE_MODE_10_BIT_ADDRESS							SSP2CON1_SSP2M_BIT3_CLR | SSP2CON1_SSP2M_BIT2_SET | SSP2CON1_SSP2M_BIT1_SET | SSP2CON1_SSP2M_BIT0_SET
#define SSP2_I2C_MASTER_MODE_CLOCK									SSP2CON1_SSP2M_BIT3_SET | SSP2CON1_SSP2M_BIT2_CLR | SSP2CON1_SSP2M_BIT1_CLR | SSP2CON1_SSP2M_BIT0_CLR
#define SSP2_RESERVED_0												SSP2CON1_SSP2M_BIT3_SET | SSP2CON1_SSP2M_BIT2_CLR | SSP2CON1_SSP2M_BIT1_CLR | SSP2CON1_SSP2M_BIT0_SET
#define SSP2_SPI_MASTER_MODE_CLOCK									SSP2CON1_SSP2M_BIT3_SET | SSP2CON1_SSP2M_BIT2_CLR | SSP2CON1_SSP2M_BIT1_SET | SSP2CON1_SSP2M_BIT0_CLR
#define SSP2_I2C_FIRMWARE_CONTROLLED_MASTER_MODE					SSP2CON1_SSP2M_BIT3_SET | SSP2CON1_SSP2M_BIT2_CLR | SSP2CON1_SSP2M_BIT1_SET | SSP2CON1_SSP2M_BIT0_SET
#define SSP2_RESERVED_1												SSP2CON1_SSP2M_BIT3_SET | SSP2CON1_SSP2M_BIT2_SET | SSP2CON1_SSP2M_BIT1_CLR | SSP2CON1_SSP2M_BIT0_CLR
#define SSP2_RESERVED_2												SSP2CON1_SSP2M_BIT3_SET | SSP2CON1_SSP2M_BIT2_SET | SSP2CON1_SSP2M_BIT1_CLR | SSP2CON1_SSP2M_BIT0_SET
#define SSP2_I2C_SLAVE_MODE_7_BIT_ADDRESS_WITH_START_AND_STOP_BIT_INTERRUPTS_ENABLED		SSP2CON1_SSP2M_BIT3_SET | SSP2CON1_SSP2M_BIT2_SET | SSP2CON1_SSP2M_BIT1_SET | SSP2CON1_SSP2M_BIT0_CLR
#define SSP2_I2C_SLAVE_MODE_10_BIT_ADDRESS_WITH_START_AND_STOP_BIT_INTERRUPTS_ENABLED	SSP2CON1_SSP2M_BIT3_SET | SSP2CON1_SSP2M_BIT2_SET | SSP2CON1_SSP2M_BIT1_SET | SSP2CON1_SSP2M_BIT0_SET


//SSP1CON2: SSP1 CONTROL REGISTER 2
#define SSP1CON2_GCEN_SET				0X80				//General Call Enable bit (in I2C Slave mode only)
#define SSP1CON2_GCEN_CLR				0X00
#define SSP1CON2_ACKSTAT_SET			0X40				//Acknowledge Status bit (in I2C mode only)
#define SSP1CON2_ACKSTAT_CLR			0X00
#define SSP1CON2_ACKDT_SET				0X20				//Acknowledge Data bit (in I2C mode only)
#define SSP1CON2_ACKDT_CLR				0X00
#define SSP1CON2_ACKEN_SET				0X10				//Acknowledge Sequence Enable bit (in I2C Master Receive mode only)
#define SSP1CON2_ACKEN_CLR				0X00
#define SSP1CON2_RCEN_SET				0X08				//Receive Enable bit (in I2C Master mode only)
#define SSP1CON2_RCEN_CLR				0X00
#define SSP1CON2_PEN_SET				0X04				//Stop Condition Enable bit (in I2C Master mode only),SCK Release Control
#define SSP1CON2_PEN_CLR				0X00
#define SSP1CON2_RSEN_SET				0X02				//Repeated Start Condition Enabled bit (in I2C Master mode only)
#define SSP1CON2_RSEN_CLR				0X00
#define SSP1CON2_SEN_SET_MASTER_MODE	0X01				//Start Condition Enabled bit (in I2C Master mode only)
#define SSP1CON2_SEN_CLR_MASTER_MODE	0X00
#define SSP1CON2_SEN_SET_SLAVE_MODE		0X01				//Start Condition Enabled bit (in I2C Master mode only)
#define SSP1CON2_SEN_CLR_SLAVE_MODE		0X00

//SSP1CON2: SSP2 CONTROL REGISTER 2
#define SSP2CON2_GCEN_SET				0X80				//General Call Enable bit (in I2C Slave mode only)
#define SSP2CON2_GCEN_CLR				0X00
#define SSP2CON2_ACKSTAT_SET			0X40				//Acknowledge Status bit (in I2C mode only)
#define SSP2CON2_ACKSTAT_CLR			0X00
#define SSP2CON2_ACKDT_SET				0X20				//Acknowledge Data bit (in I2C mode only)
#define SSP2CON2_ACKDT_CLR				0X00
#define SSP2CON2_ACKEN_SET				0X10				//Acknowledge Sequence Enable bit (in I2C Master Receive mode only)
#define SSP2CON2_ACKEN_CLR				0X00
#define SSP2CON2_RCEN_SET				0X08				//Receive Enable bit (in I2C Master mode only)
#define SSP2CON2_RCEN_CLR				0X00
#define SSP2CON2_PEN_SET				0X04				//Stop Condition Enable bit (in I2C Master mode only),SCK Release Control
#define SSP2CON2_PEN_CLR				0X00
#define SSP2CON2_RSEN_SET				0X02				//Repeated Start Condition Enabled bit (in I2C Master mode only)
#define SSP2CON2_RSEN_CLR				0X00
#define SSP2CON2_SEN_SET_MASTER_MODE	0X01				//Start Condition Enabled bit (in I2C Master mode only)
#define SSP2CON2_SEN_CLR_MASTER_MODE	0X00
#define SSP2CON2_SEN_SET_SLAVE_MODE		0X01				//Start Condition Enabled bit (in I2C Master mode only)
#define SSP2CON2_SEN_CLR_SLAVE_MODE		0X00

//SSP1CON3: SSP1 CONTROL REGISTER 3
#define SSP1CON3_ACKTIM_SET				0X80				//Acknowledge Time Status bit (I2C mode only)
#define SSP1CON3_ACKTIM_CLR				0X00
#define SSP1CON3_PCIE_SET				0X40				//Stop Condition Interrupt Enable bit (I2C mode only)
#define SSP1CON3_PCIE_CLR				0X00
#define SSP1CON3_SCIE_SET				0X20				//Start Condition Interrupt Enable bit (I2C mode only)
#define SSP1CON3_SCIE_CLR				0X00
#define SSP1CON3_BOEN_SET_SPI_SLAVE_MODE		0X10		//Buffer Overwrite Enable bit
#define SSP1CON3_BOEN_CLR_SPI_SLAVE_MODE		0X00
//In I2C Master mode: This bit is ignored
#define SSP1CON3_BOEN_SET_I2C_SLAVE_MODE		0X10
#define SSP1CON3_BOEN_CLR_I2C_SLAVE_MODE		0X00
#define SSP1CON3_SDAHT_SET				0X08				//SDA1 Hold Time Selection bit (I2C mode only)
#define SSP1CON3_SDAHT_CLR				0X00
#define SSP1CON3_SBCDE_SET				0X04				//Slave Mode Bus Collision Detect Enable bit (I2C Slave mode only)
#define SSP1CON3_SBCDE_CLR				0X00
#define SSP1CON3_AHEN_SET				0X02				//Address Hold Enable bit (I2C Slave mode only)
#define SSP1CON3_AHEN_CLR				0X00
#define SSP1CON3_DHEN_SET				0X01				//Data Hold Enable bit (I2C Slave mode only)
#define SSP1CON3_DHEN_CLR				0X00	


//SSP1CON3: SSP2 CONTROL REGISTER 3
#define SSP2CON3_ACKTIM_SET				0X80				//Acknowledge Time Status bit (I2C mode only)
#define SSP2CON3_ACKTIM_CLR				0X00
#define SSP2CON3_PCIE_SET				0X40				//Stop Condition Interrupt Enable bit (I2C mode only)
#define SSP2CON3_PCIE_CLR				0X00
#define SSP2CON3_SCIE_SET				0X20				//Start Condition Interrupt Enable bit (I2C mode only)
#define SSP2CON3_SCIE_CLR				0X00
#define SSP2CON3_BOEN_SET_SPI_SLAVE_MODE		0X10		//Buffer Overwrite Enable bit
#define SSP2CON3_BOEN_CLR_SPI_SLAVE_MODE		0X00
//In I2C Master mode: This bit is ignored
#define SSP2CON3_BOEN_SET_I2C_SLAVE_MODE		0X10
#define SSP2CON3_BOEN_CLR_I2C_SLAVE_MODE		0X00
#define SSP2CON3_SDAHT_SET				0X08				//SDA1 Hold Time Selection bit (I2C mode only)
#define SSP2CON3_SDAHT_CLR				0X00
#define SSP2CON3_SBCDE_SET				0X04				//Slave Mode Bus Collision Detect Enable bit (I2C Slave mode only)
#define SSP2CON3_SBCDE_CLR				0X00
#define SSP2CON3_AHEN_SET				0X02				//Address Hold Enable bit (I2C Slave mode only)
#define SSP2CON3_AHEN_CLR				0X00
#define SSP2CON3_DHEN_SET				0X01				//Data Hold Enable bit (I2C Slave mode only)
#define SSP2CON3_DHEN_CLR				0X00	

//SSP1MSK: SSP1 MASK REGISTER
#define SSP1MSK_MSK_BIT_7_SET			0X80				//Mask bits
#define SSP1MSK_MSK_BIT_7_CLR			0X00
#define SSP1MSK_MSK_BIT_6_SET			0X40
#define SSP1MSK_MSK_BIT_6_CLR			0X00
#define SSP1MSK_MSK_BIT_5_SET			0X20
#define SSP1MSK_MSK_BIT_5_CLR			0X00
#define SSP1MSK_MSK_BIT_4_SET			0X10
#define SSP1MSK_MSK_BIT_4_CLR			0X00
#define SSP1MSK_MSK_BIT_3_SET			0X08
#define SSP1MSK_MSK_BIT_3_CLR			0X00
#define SSP1MSK_MSK_BIT_2_SET			0X04
#define SSP1MSK_MSK_BIT_2_CLR			0X00
#define SSP1MSK_MSK_BIT_1_SET			0X02
#define SSP1MSK_MSK_BIT_1_CLR			0X00
#define SSP1MSK_MSK_BIT_0_SET			0X01
#define SSP1MSK_MSK_BIT_0_CLR			0X00

//SSP2MSK: SSP2 MASK REGISTER
#define SSP2MSK_MSK_BIT_7_SET			0X80				//Mask bits
#define SSP2MSK_MSK_BIT_7_CLR			0X00
#define SSP2MSK_MSK_BIT_6_SET			0X40
#define SSP2MSK_MSK_BIT_6_CLR			0X00
#define SSP2MSK_MSK_BIT_5_SET			0X20
#define SSP2MSK_MSK_BIT_5_CLR			0X00
#define SSP2MSK_MSK_BIT_4_SET			0X10
#define SSP2MSK_MSK_BIT_4_CLR			0X00
#define SSP2MSK_MSK_BIT_3_SET			0X08
#define SSP2MSK_MSK_BIT_3_CLR			0X00
#define SSP2MSK_MSK_BIT_2_SET			0X04
#define SSP2MSK_MSK_BIT_2_CLR			0X00
#define SSP2MSK_MSK_BIT_1_SET			0X02
#define SSP2MSK_MSK_BIT_1_CLR			0X00
#define SSP2MSK_MSK_BIT_0_SET			0X01
#define SSP2MSK_MSK_BIT_0_CLR			0X00

